apiVersion: v1
kind: Pod

metadata:
  name: my-pod

spec:
  imagePullSecrets:
    - name: ecr-secret

  containers:
    - name: my-container
      image: 450321244603.dkr.ecr.ap-south-1.amazonaws.com/dhangpt-api:latest